/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/app/about': RouteRecordInfo<'/app/about', '/app/about', Record<never, never>, Record<never, never>>,
    '/app/devices': RouteRecordInfo<'/app/devices', '/app/devices', Record<never, never>, Record<never, never>>,
    '/app/devices/': RouteRecordInfo<'/app/devices/', '/app/devices', Record<never, never>, Record<never, never>>,
    '/app/devices/[id]': RouteRecordInfo<'/app/devices/[id]', '/app/devices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/app/firmware': RouteRecordInfo<'/app/firmware', '/app/firmware', Record<never, never>, Record<never, never>>,
    '/app/models': RouteRecordInfo<'/app/models', '/app/models', Record<never, never>, Record<never, never>>,
    '/app/profile': RouteRecordInfo<'/app/profile', '/app/profile', Record<never, never>, Record<never, never>>,
    '/app/serials': RouteRecordInfo<'/app/serials', '/app/serials', Record<never, never>, Record<never, never>>,
    '/app/ssh-terminal/[deviceId]': RouteRecordInfo<'/app/ssh-terminal/[deviceId]', '/app/ssh-terminal/:deviceId', { deviceId: ParamValue<true> }, { deviceId: ParamValue<false> }>,
    '/app/users': RouteRecordInfo<'/app/users', '/app/users', Record<never, never>, Record<never, never>>,
    '/app/vendors': RouteRecordInfo<'/app/vendors', '/app/vendors', Record<never, never>, Record<never, never>>,
    '/app/wifi-templates': RouteRecordInfo<'/app/wifi-templates', '/app/wifi-templates', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/bind-device': RouteRecordInfo<'/bind-device', '/bind-device', Record<never, never>, Record<never, never>>,
  }
}
